- repo: git://github.com/dnephin/pre-commit-golang
  rev: master
  hooks:
    - id: go-fmt
    - id: go-lint
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0  # Use the ref you want to point at
    hooks:
    - id: trailing-whitespace
    - id: detect-private-key
    - id: end-of-file-fixer
- repo: https://github.com/thlorenz/doctoc.git
  rev: v1.4.0
  hooks:
    - id: doctoc
      name: Add TOC for md files
      files: ^README\.md$
      args:
        - "--maxlevel"
        - "2"
